SELECT DISTINCT
A.CUSTOMERID,
A.CUSTOMERNAME,
A.SHORTNAME,
A.NATIONALTAXNUMBER,
A.ACCOUNTGROUPID,
A.STATETAXNUMBER,
A.CITYTAXNUMBER,
A.CUSTOMERTYPEID,
A.STREETADDRESS,
A.DISTRICT,
A.CITY,
A.STATE,
A.COUNTRY,
A.POSTALCODE,
A.POBOX,
A.BANKID,
A.BANKBRANCHNUMBER,
A.BANKACCOUNTNUMBER,
A.TELEPHONENUMBER1,
A.TELEPHONENUMBER2,
A.SUFRAMANUMBER,
A.IPISUSPENSION,
A.ICMSPAYER,
A.CREDITLIMIT,
A.CONTACTPERSON1,
A.GENDER,
A.BIRTHDATE,
A.MARITALSTATUS,
A.FREEOFCHARGETYPEID,
A.LOGICALEXCLUSION,
A.DELETIONFLAG,
A.CREATIONDATE ,
A.STREETADDRESSNUMBER
FROM STGCUSTOMER A
LEFT JOIN STGCUSTOMERSALESAREA B ON A.CUSTOMERID = B.CUSTOMERID
LEFT JOIN STGCUSTOMERSALESAREAPARTNER C ON B.CUSTOMERID = C.CUSTOMERID
          AND B.SALESORGANIZATIONID   = C.SALESORGANIZATIONID
          AND B.DISTRIBUTIONCHANNELID = C.DISTRIBUTIONCHANNELID
          AND B.DIVISIONID  = C.DIVISIONID
		  --AND B.GOODFORCUSTOMER = 1
          AND C.PARTNERFUNCTIONID = 'RE'
          AND C.GOODFORPARTNERFUNCTION = 1
LEFT JOIN STGCUSTOMER D ON C.PARTNERCUSTOMERID = D.CUSTOMERID
WHERE A.CUSTOMERID IN (SELECT A1.KUNNR FROM TB_PARAM_CLIENTES A1 WHERE A1.ODS_TIMESTMP >= dateadd(D, -4, convert--(DATE, (SELECT DT_CARGA FROM TB_PARAM_DTCARGA))) )