SELECT DISTINCT 
STGCUSTOMERSALESAREA.DELETIONFLAG, 
STGCUSTOMERSALESAREA.CUSTOMERID, 
STGCUSTOMERSALESAREA.SALESORGANIZATIONID, 
STGCUSTOMERSALESAREA.ADMINISTRATIVEBLOCK, 
STGCUSTOMERSALESAREA.BINDINGCUSTOMERID, 
STGCUSTOMERSALESAREA.ALLOWEDSALESUNIT, 
STGCUSTOMERSALESAREA.SALESOFFICEID, 
STGCUSTOMERSALESAREA.CUSTOMERGROUPID, 
STGCUSTOMERSALESAREA.ROUTELEADTIME, 
STGCUSTOMERSALESAREA.ROUTEID, 
STGCUSTOMERSALESAREA.MINIMUMORDERVALUE, 
STGCUSTOMERSALESAREA.MINIMUMORDERWEIGHT, 
STGCUSTOMERSALESAREA.DISTRIBUTIONCHANNELID, 
STGCUSTOMERSALESAREA.DIVISIONID, 
STGCUSTOMERSALESAREA.STOREEAN, 
STGCUSTOMERSALESAREA.LOSSBLOCK, 
STGCUSTOMERSALESAREA.REBATEBLOCK, 
STGCUSTOMERSALESAREA.PAYMENTTERMID, 
STGCUSTOMERSALESAREA.DELIVERYPLANT, 
STGCUSTOMERSALESAREA.SHIPPINGCONDITIONID, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMEMONDAYAFTUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMETUESDAYAFTUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMEWEDNESDAYAFTUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMETHURSDAYAFTUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMEFRIDAYAFTUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMESATURDAYAFTUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMESUNDAYAFTUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMEMONDAYMORNFROM, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMETUESDAYMORNFROM, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMEWEDNESDAYMORNFROM, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMETHURSDAYMORNFROM, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMEFRIDAYMORNFROM, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMESATURDAYMORNFROM, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMESUNDAYMORNFROM, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMEMONDAYMORNUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMEMONDAYAFTFROM, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMETUESDAYMORNUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMETUESDAYAFTFROM, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMEWEDNESDAYMORNUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMEWEDNESDAYAFTFROM, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMETHURSDAYMORNUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMETHURSDAYAFTFROM, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMEFRIDAYMORNUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMEFRIDAYAFTFROM, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMESATURDAYMORNUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMESATURDAYAFTFROM, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMESUNDAYMORNUNTIL, 
STGCUSTOMERUNLOADINGPOINT.DELIVERYTIMESUNDAYAFTFROM,
A.PARTNERFUNCTIONID, 
A.PARTNERCUSTOMERID, 
B.PARTNERFUNCTIONID,
B.PARTNERCUSTOMERID
FROM
 STGCUSTOMERSALESAREA LEFT JOIN STGCUSTOMERUNLOADINGPOINT ON STGCUSTOMERSALESAREA.CUSTOMERID = STGCUSTOMERUNLOADINGPOINT.CUSTOMERID AND   
CASE WHEN UPPER(STGCUSTOMERUNLOADINGPOINT.UNLOADINGPOINT) IN ('DANONE DAIRY BR')    THEN '2400'
		WHEN UPPER(STGCUSTOMERUNLOADINGPOINT.UNLOADINGPOINT) IN ('DANONE WATER BR', 'DANONE WATERS BR')  THEN '2410'
		WHEN UPPER(STGCUSTOMERUNLOADINGPOINT.UNLOADINGPOINT) IN ('DANONE BABY BR', 'SUPPORT BABY BR')   THEN '2420'
		WHEN UPPER(STGCUSTOMERUNLOADINGPOINT.UNLOADINGPOINT) IN ('DANONE MEDICAL BR', 'SUPPORT MEDICAL BR') THEN '2430'
ELSE NULL END = STGCUSTOMERSALESAREA.SALESORGANIZATIONID
LEFT JOIN (SELECT CUSTOMERID , SALESORGANIZATIONID, DISTRIBUTIONCHANNELID ,  DIVISIONID , PARTNERFUNCTIONID , PARTNERCUSTOMERID FROM STGCUSTOMERSALESAREAPARTNER
WHERE  GOODFORPARTNERFUNCTION = 1 AND PARTNERFUNCTIONID = 'Z2' ) A  ON
STGCUSTOMERSALESAREA.CUSTOMERID = A.CUSTOMERID
          AND STGCUSTOMERSALESAREA.SALESORGANIZATIONID   = A.SALESORGANIZATIONID
          AND STGCUSTOMERSALESAREA.DISTRIBUTIONCHANNELID = A.DISTRIBUTIONCHANNELID
          AND STGCUSTOMERSALESAREA.DIVISIONID = A.DIVISIONID         
LEFT JOIN (SELECT CUSTOMERID , SALESORGANIZATIONID, DISTRIBUTIONCHANNELID ,  DIVISIONID , PARTNERFUNCTIONID , PARTNERCUSTOMERID FROM STGCUSTOMERSALESAREAPARTNER
WHERE GOODFORPARTNERFUNCTION = 1 AND PARTNERFUNCTIONID = 'ZQ' ) B  ON
STGCUSTOMERSALESAREA.CUSTOMERID = B.CUSTOMERID
          AND STGCUSTOMERSALESAREA.SALESORGANIZATIONID   = B.SALESORGANIZATIONID
          AND STGCUSTOMERSALESAREA.DISTRIBUTIONCHANNELID = B.DISTRIBUTIONCHANNELID
          AND STGCUSTOMERSALESAREA.DIVISIONID = B.DIVISIONID
WHERE 
 STGCUSTOMERSALESAREA.SALESORGANIZATIONID BETWEEN '2300' AND '2499' AND
STGCUSTOMERSALESAREA.GOODFORSALESORG = 1
AND STGCUSTOMERSALESAREA.CUSTOMERID IN (SELECT A1.KUNNR FROM TB_PARAM_CLIENTES A1 WHERE A1.ODS_TIMESTMP >= dateadd(D, -4, convert(DATE, (SELECT DT_CARGA FROM TB_PARAM_DTCARGA))) )