SELECT 
SO.DT_VDA, 
SO.CD_FORNECEDOR_PRODUTO_CODIGO, 
SO.QT_VDA, 
SO.VL_VDA_DIS, 
SO.NR_CNPJ, 
SO.NR_CNPJ_CLI, 
SO.CD_VENDEDOR, 
SO.NR_ANO, 
SO.NR_MES, 
SO.TP_TRA_MOV, 
SO.QT_TONELADAS, 
SO.QT_CAIXAS, 
SO.COD_UNIDADE_NEGOCIO  
FROM
 TB_SELLOUT_VENDAS_BI SO
WHERE
 SO.DT_VDA BETWEEN $$DT_INI AND $$DT_FIM